package com.ledgerflow.order.repo;

import java.util.UUID;

import org.springframework.data.repository.reactive.ReactiveCrudRepository;
import org.springframework.stereotype.Repository;

import com.ledgerflow.order.model.entity.OrderEntity;

/**
 * Spring Data repository for the {@code orders} table.
 *
 * <p>{@code save()} relies on {@link OrderEntity#isNew()}
 * ({@code Persistable}) to choose insert vs. update, since the entity's id
 * is assigned by the application, not generated by the database.
 */
@Repository
public interface OrderRepository extends ReactiveCrudRepository<OrderEntity, UUID> {
}
