package com.ledgerflow.order.model.entity;

import java.math.BigDecimal;
import java.util.UUID;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.domain.Persistable;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Line item of an order, persisted via Spring Data R2DBC in its own
 * {@code order_items} row (one row per item, foreign-keyed to {@code orders}).
 *
 * <p>Implements {@link Persistable} because the id is assigned by the
 * application ({@link #forInsert}) rather than generated by the database: a
 * plain {@code ReactiveCrudRepository.save()} decides insert vs. update from
 * {@link #isNew()}, and with a client-assigned id that would otherwise
 * always look like an update. {@code isNew} is {@code @Transient} so it is
 * never read back from a column — Spring Data instantiates rows loaded from
 * the database through the no-args constructor, leaving it at its default
 * ({@code false}), while {@link #forInsert} explicitly sets it {@code true}.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
@Table("order_items")
public class OrderItemEntity implements Persistable<UUID> {

    @Id
    private UUID id;

    @Column("order_id")
    private UUID orderId;

    @NotBlank
    @Column("product_id")
    private String productId;

    @Positive
    @Column("quantity")
    private int quantity;

    @NotNull
    @PositiveOrZero
    @Column("unit_price")
    private BigDecimal unitPrice;

    @Transient
    @Builder.Default
    private boolean isNew = false;

    /**
     * Builds a not-yet-persisted item for {@code orderId}, with a freshly
     * assigned id and {@link #isNew()} forced to {@code true}.
     */
    public static OrderItemEntity forInsert(UUID orderId, String productId, int quantity, BigDecimal unitPrice) {
        return OrderItemEntity.builder()
                .id(UUID.randomUUID())
                .orderId(orderId)
                .productId(productId)
                .quantity(quantity)
                .unitPrice(unitPrice)
                .isNew(true)
                .build();
    }

    @Override
    public boolean isNew() {
        return isNew;
    }
}
